language: node_js
node_js:
  - '0.10'
  - '0.12'
  - iojs-v2
  - iojs-v3
  - '4'
matrix:
  allow_failures:
    - node_js: iojs-v3
    - node_js: '4'
deploy:
  provider: npm
  email: mahnunchik@gmail.com
  api_key:
    secure: fGFoD2S5JYeeLNalPNY49Jf7wUW8FNNxPs/2BeSmnikUotE/bzPpIsCrqsW0XyFAtNKjeV9AVI5zE5AKaJcwy2/uGvUK/q7ql3WG+YlIGwXME/HJvAocNql8+RXWBxDKbXXaJ15HSlWEkuTG/ixG2qUpMrZRDXD9EbTBVTOSLJM=
  on:
    tags: true
    repo: mahnunchik/gulp-responsive
before_install:
  - curl -s https://raw.githubusercontent.com/lovell/sharp/master/preinstall.sh | sudo bash -
