language: node_js
node_js:
- '0.10'
- '0.12'
- iojs
deploy:
  provider: npm
  email: mahnunchik@gmail.com
  api_key:
    secure: dToBKY9QRznavUUBBcttoOKbLV2vGB8AxHUhGT8YbujkI7wPM4lyJv0VYlGOUdOL4F7D8WeP+aIB4n7YNqHOWxi+XfGjC6Qpw+GlwL00ZBzbbQBhUshJq00Wq8SVfrAZcYQXwVM969cw8EaiRfAGIlSKdzv59B4pJGzhj2holNs=
  on:
    branch: master
    tags: true
    all_branches: true
    repo: mahnunchik/gulp-responsive
before_install:
  - curl -s https://raw.githubusercontent.com/lovell/sharp/master/preinstall.sh | sudo bash -
